# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0debbfaae78e714476cbb5978e81624a3cf1b2642fb09e9f0c6cb48e10e2b566fb132840c2f2ed093eb6319480b581123933b99844f0a09298f2a298c6a1b821

test:
  secret_key_base: de27274c52d2539bf8a5b49fb7ca3a8030098bdd6ce484d5fe87d27f3d81ebf8b2fa2817338e24df34a089f79e99410e16eeda7a9ff778b0bb058f00c575f4e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
